### PR TITLE
awanderlyss WEEK 05 DAY 05 HOMEWORK

### PR DESCRIPTION
**Pull request by awanderlyss**
Comfort: 4
Completeness: 5

I would like some direction on how I would go about rendering multiple paths in the application layout.

### CODE REVIEW

**Comment by JosephinaTavera** [comment]
:+1  Awesome job with assignment, you have a good grasp with Rails.    Not to sure on your question,   I believe partials would be one way to display multiples on application.

**Comment by JosephinaTavera** [comment]
Here is a linked for nested layouts

http://railsguides.net/rails-nested-layouts/

**Comment by awanderlyss** [comment]
Thank you!!!

**Comment by JosephinaTavera** [comment]
Your welcome 😁

**Pull request closed without merging**
